name = "site-lema-docs"
page = "https://lema-ai.notion.site/Lema-s-Wiki-e8bf7f0655c14bfeb90f669bc9711e26?pvs=4"

[site]
  [[site.meta]]
  name = "Lema Docs"
  content = "Real-Time Third-Party Risk Management"

  # [[site.inject.head.link]]
  # rel="icon" 
  # sizes="16x16"
  # type="image/png"
  # href="/example/favicon-16x16.png"
  
  # the following injects this tag in the in the <body>:
  #   <script src="custom-script.js" type="text/javascript"></script>
  # note that all href / src files are copied to the root of the site folder 
  # regardless of their original path
  # [[site.inject.body.script]]
  # type="text/javascript"
  # src="/example/custom-script.js"

